apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql-container
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
---
apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin-pod
spec:
  containers:
    - name: phpmyadmin-container
      image: phpmyadmin/phpmyadmin
      env:
        - name: PMA_HOST
          value: mysql-pod
        - name: MYSQL_ROOT_PASSWORD
          value: password
